/**
 * Stormreach Coast — Act II field data.
 * A walkable cliff after the Verdant waystone. The harbor vault is a face,
 * not a door you can open. Scenes live in act2-scenes.js.
 */
(function (Emberwake) {
  'use strict';

  Emberwake.registerRegion({
    id: 'stormreach',
    act: 2,
    title: 'Bottled Sky',
    name: 'Stormreach Coast',
    landmarks: [
      { id: 'landing', kind: 'roost', x: 0, z: 9, clear: 2.6 },
      { id: 'harbor-vault', kind: 'vault', x: 0.2, z: 0.15, clear: 3.2 },
    ],
    pools: [
      {
        id: 'harbor-leak',
        element: 'lightning',
        name: 'Harbor Leak',
        short: 'Leak',
        region: 'stormreach',
        x: 5.6,
        z: 3.4,
        xp: 38,
        rot: 0.8,
        strain: 16,
        hint: 'Lightning the vault failed to cork. It pools on the shale and looks for a mouth.',
        line: 'You drink the leak. The seal on the door does not notice. Lira’s teeth taste of copper and clerks.',
      },
      {
        id: 'spire-bone',
        element: 'lightning',
        name: 'Spire Bone',
        short: 'Spire',
        region: 'stormreach',
        x: -6.4,
        z: 6.6,
        xp: 32,
        rot: 0.55,
        strain: 14,
        hint: 'A rib of the cliff that still argues with the weather.',
        line: 'The spire gives up its lightning. The argument moves behind her eyes. The cliff keeps the scar.',
      },
      {
        id: 'yard-slag',
        element: 'fire',
        name: 'Yard Slag',
        short: 'Slag',
        interior: 'concord-yard',
        region: 'stormreach',
        concord: true,
        x: 0,
        z: -1.15,
        xp: 30,
        rot: 0.65,
        strain: 14,
        hint: 'Fire the Concord licensed and could not keep. Drinking it puts your name on their leak.',
        line: 'You drink the yard slag. The licence does not hold. The rot learns the mouth that took it.',
      },
      {
        id: 'marrow-leak',
        element: 'water',
        name: 'Engine Leak',
        short: 'Leak',
        interior: 'ashen-marrow',
        region: 'stormreach',
        x: 0.2,
        z: -0.8,
        xp: 24,
        rot: 0.7,
        strain: 12,
        hint: 'What the harbor bottled and the ash would not keep. Feeding it heals nothing the scar will not charge.',
        line: 'You feed the engine. The leak goes quiet. The scar in her takes the mouthful and does not give it back.',
      },
    ],
    beats: [
      {
        id: 'vault-face',
        scene: 'vault-face',
        x: 0.2,
        z: 2.15,
        r: 2.3,
        toast: 'The harbor vault looks back.',
      },
      {
        id: 'merge-tease',
        scene: 'merge-tease',
        x: 0,
        z: 5.4,
        r: 2.5,
        toast: 'Two elements try to share a word.',
      },
      {
        id: 'vesper-duel',
        scene: 'vesper-duel',
        x: 7.4,
        z: 8.1,
        r: 2.8,
        toast: 'Someone on the shale already knows your hunger.',
      },
      {
        id: 'kestrel-ask',
        scene: 'kestrel-ask',
        x: -2.4,
        z: 8.4,
        r: 2.2,
        toast: 'A wing holds over the roost.',
      },
    ],
  });
})(window.Emberwake);
